#!/bin/sh
# GENERATED by tools/generate-pi.py — installs the mismAgent pi packaging.
#   install.sh <project-root>     skills, prompts, agents and AGENTS.md into the project
#   install.sh --package <dir>    an anchored pi package (skills + prompts) for `pi install <dir>`
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
usage() { echo "usage: install.sh <project-root> | install.sh --package <dir>" >&2; exit 2; }
check_path() {  # the path is written quoted into commands: refuse what would break the quoting
  case "$1" in *'"'*|*'`'*|*'$'*|*'\'*) echo "install.sh: the path must not contain a quote, backtick, dollar or backslash" >&2; exit 2 ;; esac
}
anchor() {  # every path into the skills -> this installation's absolute skills directory
  ESC=$(printf '%s' "$1" | sed 's/[|&\\]/\\&/g')
  shift
  for f in "$@"; do
    [ -f "$f" ] || continue
    sed "s|@@MISMAGENT_SKILLS@@|$ESC|g" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  done
}
case "${1:-}" in
  "") usage ;;
  --with-cross-deploy) usage ;;
  --package)
    [ -n "${2:-}" ] && [ -z "${3:-}" ] || usage
    mkdir -p "$2"
    PKG=$(cd "$2" && pwd)
    check_path "$PKG"
    rm -rf "$PKG/skills" "$PKG/prompts"
    cp -R "$HERE/skills" "$HERE/prompts" "$HERE/package.json" "$PKG/"
    anchor "$PKG/skills" "$PKG"/skills/mismagent-*/SKILL.md "$PKG"/skills/mismagent-*/references/*.md \
      "$PKG"/prompts/mismagent-*.md
    echo "mismAgent pi package written to $PKG — install it with: pi install \"$PKG\""
    exit 0 ;;
esac
case "${2:-}" in
  "") ;;
  --with-cross-deploy)
    echo "install.sh: --with-cross-deploy was removed in v0.18.0 (cross-deploy is no longer a module;" \
      "keep such contracts as project files). Run: install.sh <project-root>" >&2
    exit 2 ;;
  *) usage ;;
esac
mkdir -p "$1"
TARGET=$(cd "$1" && pwd)
check_path "$TARGET"

mkdir -p "$TARGET/.agents/skills" "$TARGET/.pi/prompts" "$TARGET/.pi/agents"
# skills retired in v0.18.0: remove them from an upgraded installation
for old in create-contract seam-cross-deploy seam-in-process; do
  rm -rf "$TARGET/.agents/skills/mismagent-$old"
done
for d in "$HERE"/skills/*/; do
  name=$(basename "$d")
  rm -rf "$TARGET/.agents/skills/$name"
  cp -R "$d" "$TARGET/.agents/skills/$name"
done
cp "$HERE"/prompts/*.md "$TARGET/.pi/prompts/"
cp "$HERE"/agents/*.md "$TARGET/.pi/agents/"

if [ -f "$TARGET/AGENTS.md" ]; then
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
  echo "AGENTS.md already exists -> wrote AGENTS.mismagent.md (merge it into yours)."
else
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.md"
fi
anchor "$TARGET/.agents/skills" "$TARGET"/.agents/skills/mismagent-*/SKILL.md \
  "$TARGET"/.agents/skills/mismagent-*/references/*.md "$TARGET"/.pi/prompts/mismagent-*.md \
  "$TARGET"/.pi/agents/mismagent-*.md "$TARGET/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
echo "mismAgent (pi) installed into $TARGET — verify with /skill:mismagent-explore."
echo "[agent] steps need pi's subagent example extension (AGENTS.md, Setup) with agentScope 'both'."
