#!/bin/sh
# GENERATED by tools/generate-pi.py — installs the mismAgent pi packaging into a project.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
TARGET=${1:?usage: install.sh <project-root> [--with-cross-deploy]}
WITH_CROSS=false
[ "${2:-}" = "--with-cross-deploy" ] && WITH_CROSS=true

mkdir -p "$TARGET/.agents/skills" "$TARGET/.pi/prompts" "$TARGET/.pi/agents"
for d in "$HERE"/skills/*/; do
  name=$(basename "$d")
  case "$name" in
    mismagent-create-contract|mismagent-seam-cross-deploy)
      $WITH_CROSS || continue ;;
  esac
  rm -rf "$TARGET/.agents/skills/$name"
  cp -R "$d" "$TARGET/.agents/skills/$name"
done
cp "$HERE"/prompts/*.md "$TARGET/.pi/prompts/"
cp "$HERE"/agents/*.md "$TARGET/.pi/agents/"

if [ -f "$TARGET/AGENTS.md" ]; then
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
  echo "AGENTS.md already exists -> wrote AGENTS.mismagent.md (merge it into yours)."
else
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.md"
fi
echo "mismAgent (pi) installed into $TARGET — verify with /skill:mismagent-explore."
echo "[agent] steps need pi's subagent example extension (AGENTS.md, step 0) with agentScope 'both'."
