#!/bin/sh
# GENERATED by tools/generate-codex.py — installs the mismAgent Codex packaging into a project.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
TARGET=${1:?usage: install.sh <project-root>}
case "${2:-}" in
  "") ;;
  --with-cross-deploy)
    echo "install.sh: --with-cross-deploy was removed in v0.18.0 (cross-deploy is no longer a module;"       "keep such contracts as project files). Run: install.sh <project-root>" >&2
    exit 2 ;;
  *) echo "usage: install.sh <project-root>" >&2; exit 2 ;;
esac

mkdir -p "$TARGET/.agents/skills" "$TARGET/.codex/agents"
# skills retired in v0.18.0: remove them from an upgraded installation
for old in create-contract seam-cross-deploy seam-in-process; do
  rm -rf "$TARGET/.agents/skills/mismagent-$old"
done
for d in "$HERE"/skills/*/; do
  name=$(basename "$d")
  rm -rf "$TARGET/.agents/skills/$name"
  cp -R "$d" "$TARGET/.agents/skills/$name"
done
cp "$HERE"/agents/*.toml "$TARGET/.codex/agents/"

if [ -f "$TARGET/AGENTS.md" ]; then
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
  echo "AGENTS.md already exists -> wrote AGENTS.mismagent.md (merge it into yours)."
else
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.md"
fi
echo "mismAgent (Codex) installed into $TARGET — verify with /skills (expect mismagent-explore)."
