#!/bin/sh
# GENERATED by tools/generate-codex.py — installs the mismAgent Codex packaging into a project.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
[ -n "${1:-}" ] || { echo "usage: install.sh <project-root>" >&2; exit 2; }
case "${2:-}" in
  "") ;;
  --with-cross-deploy)
    echo "install.sh: --with-cross-deploy was removed in v0.18.0 (cross-deploy is no longer a module;"       "keep such contracts as project files). Run: install.sh <project-root>" >&2
    exit 2 ;;
  *) echo "usage: install.sh <project-root>" >&2; exit 2 ;;
esac
mkdir -p "$1"
TARGET=$(cd "$1" && pwd)
SKILLS="$TARGET/.agents/skills"
# the path is written quoted into commands and inside the agents' TOML '''...''' strings
case "$SKILLS" in *'"'*|*'`'*|*'$'*|*'\'*|*"'''"*) echo "install.sh: the path must not contain a double quote, backtick, dollar, backslash or '''" >&2; exit 2 ;; esac

mkdir -p "$TARGET/.agents/skills" "$TARGET/.codex/agents"
# skills retired in v0.18.0: remove them from an upgraded installation
for old in create-contract seam-cross-deploy seam-in-process; do
  rm -rf "$TARGET/.agents/skills/mismagent-$old"
done
for d in "$HERE"/skills/*/; do
  name=$(basename "$d")
  rm -rf "$TARGET/.agents/skills/$name"
  cp -R "$d" "$TARGET/.agents/skills/$name"
done
cp "$HERE"/agents/*.toml "$TARGET/.codex/agents/"

if [ -f "$TARGET/AGENTS.md" ]; then
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
  echo "AGENTS.md already exists -> wrote AGENTS.mismagent.md (merge it into yours)."
else
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.md"
fi
# anchor every path into the skills to this installation: absolute, so it works from any cwd
ESC=$(printf '%s' "$SKILLS" | sed 's/[|&\]/\&/g')
for f in "$SKILLS"/mismagent-*/SKILL.md "$SKILLS"/mismagent-*/references/*.md "$TARGET"/.codex/agents/mismagent-*.toml          "$TARGET/AGENTS.md" "$TARGET/AGENTS.mismagent.md"; do
  [ -f "$f" ] || continue
  sed "s|@@MISMAGENT_SKILLS@@|$ESC|g" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done
echo "mismAgent (Codex) installed into $TARGET — verify with /skills (expect mismagent-explore)."
