#!/bin/sh
# GENERATED by tools/generate-codex.py — installs the mismAgent Codex packaging into a project.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
[ -n "${1:-}" ] && [ -z "${2:-}" ] || { echo "usage: install.sh <project-root>" >&2; exit 2; }
mkdir -p "$1"
TARGET=$(cd "$1" && pwd)
SKILLS="$TARGET/.agents/skills"
# the path is written quoted into commands and inside the agents' TOML '''...''' strings
case "$SKILLS" in *'"'*|*'`'*|*'$'*|*'\'*|*"'''"*) echo "install.sh: the path must not contain a double quote, backtick, dollar, backslash or '''" >&2; exit 2 ;; esac

mkdir -p "$SKILLS" "$TARGET/.codex/agents"
# the mismagent- names are this packaging's: replace them whole, so a retired piece goes too
rm -rf "$SKILLS"/mismagent-* "$TARGET"/.codex/agents/mismagent-*.toml
cp -R "$HERE"/skills/mismagent-* "$SKILLS/"
cp "$HERE"/agents/*.toml "$TARGET/.codex/agents/"

if [ -f "$TARGET/AGENTS.md" ]; then
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.mismagent.md"
  echo "AGENTS.md already exists -> wrote AGENTS.mismagent.md (merge it into yours)."
else
  cp "$HERE/AGENTS.md" "$TARGET/AGENTS.md"
fi
# anchor every path into the skills to this installation: absolute, so it works from any cwd
ESC=$(printf '%s' "$SKILLS" | sed 's/[|&\]/\&/g')
for f in "$SKILLS"/mismagent-*/SKILL.md "$SKILLS"/mismagent-*/references/*.md \
         "$SKILLS"/mismagent-*/scripts/*.py "$TARGET"/.codex/agents/mismagent-*.toml \
         "$TARGET/AGENTS.md" "$TARGET/AGENTS.mismagent.md"; do
  [ -f "$f" ] || continue
  sed "s|@@MISMAGENT_SKILLS@@|$ESC|g" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done
chmod +x "$SKILLS/mismagent-build/scripts/mm.py"
echo "mismAgent (Codex) installed into $TARGET — verify with /skills (expect mismagent-build)."
